### ISSUE TITLE
Add a restart button and automatic restart on death

### ISSUE THREAD

**Issue by dbaelz** [tkuenneth/compose_dash#1]
Right now, the game is a rogue-like one shot experience. An option to restart the level would make my player experience even better. It would be great to add:
- A restart button that restarts the current level at any time to the initial state
- An automatic restart of the level when the player dies

<br>
...and yes, I need it because I'm a bad player and got hit by a diamond. :joy:

**Comment by tkuenneth** [comment]
Thanks for creating this issue. I am confident to push a solution by Sunday. Happy weekend.

**Comment by tkuenneth** [comment]
Restart-Button added. See https://github.com/tkuenneth/compose_dash/commit/bc5f189b7d90ae3cfc2b12290e8214760e2765ba

Thanks for suggesting.
